Changed python config parameter to look at adot python lib
aws/amazon-cloudwatch-agent-operator pull request #108
Opened 2024-03-06 20:58 UTC by okankoAMZ

*Description of changes:*
Changed python config parameter to look at adot python lib

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-06 21:18 UTC, lisguo requested changes

2024-03-06 21:18 UTC, lisguo commented on versions.txt
> +public.ecr.aws/aws-observability/adot-autoinstrumentation-python:v0.0.1
this should stay `aws-otel-python-instrumentation` but set it equal to `v0.0.1`

2024-03-06 21:18 UTC, lisguo commented on main.go
> +	autoInstrumentationPythonImageRepository = "public.ecr.aws/aws-observability/adot-autoinstrumentation-python:v0.0.1"
this should just be the repository, not including the version

2024-03-07 20:37 UTC, sky333999 commented on helm/values.yaml
>        tag: 0.43b0
Doesnt this need to be updated too?

2024-03-07 20:57 UTC, sky333999 approved these changes

2024-03-07 21:20 UTC, lisguo approved these changes

2024-03-07 21:20 UTC, merged